### ISSUE TITLE
Talk Idea: Pivotal's Product Map

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal/cf-onboarding#103]
What are all the different products we make? Which are closed source and which are open source?

**Comment by dsabeti** [comment]
Ideas:
- The Stevenson slide deck could be a useful resource for explaining the different teams, what they all work on (a bit about product), what's open/closed source, etc.
- There's a product map out there somewhere. @sjolicoeur thinks he might know where to find one.
- AMA with a product director. Let's reach out to a few of them and see if they can commit to short meeting during the Onboarding weeks every once in a while.

**Comment by dsabeti** [comment]
We tried this during the August Onboarding with Amit. It was structured a bit as an AMA with a product director. It ran long, which means that folks were really interested in hearing about this.

One small concern: depending on the product director, you could end up focusing on some really different things.

**Comment by andrewedstrom** [comment]
@dsabeti could be okay that the focus is different. No matter what, participants will come out of the talk with more context than they came in with

**Comment by ljfranklin** [comment]
We have a Product Map column in our talk spreadsheet now: https://docs.google.com/spreadsheets/d/1Sto5f2PC7u2kRZJlm91OAZ1jYwN9mqiNFGFOsAKb8g0/edit#gid=1492001285. We've also run this talk a couple times now. Closing this out.
