### ISSUE TITLE
Ideas for boxes & lines format and scheduling

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal/cf-onboarding#105]
These are ideas captured during the retro for the February onboarding week. Feel free to add more in the comments below.

- Do boxes and lines earlier in the week, e.g. do the boxes and lines for BOSH before the BOSH stories.
- Bookend the epics by giving boxes and lines as epic kickoff talks, then have Q&A time after participants have completed the epic where they can reinforce their new knowledge

**Comment by dsabeti** [comment]
We're thinking something like this:
- CF Boxes and Lines on Tuesday morning, to coincide with the stories about pushing apps.
- BOSH Boxes and Lines on Wednesday morning, to coincide with the stories about troubleshooting and working with BOSH (scaling up, screwing with the bosh agent, etc.)

**Comment by dsabeti** [comment]
We starting to think that we should prepare some slides or other materials for giving this talk. Eventually, any facilitator could do boxes and lines. It would also be great if engineering teams could send someone to give boxes and lines.

**Comment by dsabeti** [comment]
We're going to try this out during one of the upcoming onboarding weeks in SF.

**Comment by dsabeti** [comment]
We've actually ended up scheduling these talks closer to the end of the day. Still figuring out how we like it.

**Comment by bwinter** [comment]
How can we turn this into more of a "curriculum setup" style artifact. As a relatively new facilitator I have no visibility into this story and it's valuable suggestions.

**Comment by bwinter** [comment]
I love that I have seen all of these comments from other facilitators.

> Eventually, any facilitator could do boxes and lines.

Garama in NYC basically does all the boxes and lines.

> It would also be great if engineering teams could send someone to give boxes and lines.

Nick Wei has pushed to get these boxes and lines saved into artifacts so we can try and used videos for boxes and lines followed up with general Q&A by facilitators to fill the "questions" gap that videos lose.

I think Github Issues isn't ideal for tracking these experiments, they get buried over time. Think I would prefer an "experiments" doc that acts as a "current state of the world".

As such, I am going to close this thing and make an experiments doc.
