### ISSUE TITLE
Create tracker stories/epics with suggestions for exploration days

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal/cf-onboarding#106]
In the retro for the February onboarding week, participants expressed that they would have liked some suggestions for topics to explore during the final days of the week. Here are some ideas we captured in that meeting:

- Make a bosh release
- Make a Concourse resource
- OS Manager deploy
- Create a tile
- PKS
- CFCR 
- Using PWS
- Container Networking
- CF Archeology (find all components via SSH)

**Comment by dsabeti** [comment]
Other ideas:
- Service Broker API
- Debugging techniques specific to CF (e.g. `cfdot`, `veritas`)

**Comment by dsabeti** [comment]
I think all we need to do is write a story with this list, and links to resources to get people started.

**Comment by dsabeti** [comment]
@sjolicoeur @andrewedstrom, is this story done?

**Comment by andrewedstrom** [comment]
Yes, as of https://github.com/pivotal-cf/onboarding/pull/112
