### ISSUE TITLE
Meeting for participants to do a "show and tell" at the end of each day

### ISSUE THREAD

**Issue by andrewedstrom** [pivotal/cf-onboarding#107]
This was brought up as a suggestion in the retro for the February onboarding week

**Comment by dsabeti** [comment]
Between this and the two daily check-ins, we think this would be a bit too much of commitment for facilitators. We're thinking about twice a week -- maybe Wednesday and Friday.

**Comment by dsabeti** [comment]
We're going to try this at the end of next week's Onboarding and see how it goes.

**Comment by dsabeti** [comment]
@njbennett, how did this go last week?

**Comment by ljfranklin** [comment]
This hasn't really come up since the initial suggestion, participants have done a fair job of sharing learnings as they go. Going to close this for now and see if it comes up again.
