### ISSUE TITLE
Need to specify username when setting up redis server

### ISSUE THREAD

**Issue by border-buddy** [pivotal/cf-onboarding#11]
If you create your redis db with RedisLabs, you need to specify your username when creating the cf service via `cf cups`...e.g.

```
cf cups redis -p "host, port, username, password"
``` 

This username will be whatever email address you used to sign up for the service with.

(https://www.pivotaltracker.com/story/show/142993563)

**Comment by border-buddy** [comment]
Totally did not mean to comment on this issue with border-buddy account, whoops. This is Oliver and Mike.

**Comment by keaty** [comment]
Story has been updated to include username in the instructions
