### ISSUE TITLE
brew install command for bosh-cli incorrect

### ISSUE THREAD

**Issue by jzlwang** [pivotal/cf-onboarding#115]
The [tracker story](https://www.pivotaltracker.com/story/show/157165700) shows: 

![image](https://user-images.githubusercontent.com/10158476/39440216-06f24da6-4c5f-11e8-8392-ef713a55a0fd.png)

it should say 

> brew install cloudfoundry/tap/bosh-cli

**Comment by dsabeti** [comment]
This commit should fix it: https://github.com/pivotal-cf/onboarding/commit/927aa4e29ae7c6de7ccacc9d426e388fa684da13
