### ISSUE TITLE
bbl create-lbs command no longer exists

### ISSUE THREAD

**Issue by jzlwang** [pivotal/cf-onboarding#117]
it looks like bbl updated such that the `create-lbs` command no longer works. In [this story](https://www.pivotaltracker.com/story/show/157165708), we should replace

`$ bbl create-lbs --type cf --domain some-domain.com --cert cert.pem --key key.pem`

with

```
$ bbl plan --lb-type cf --lb-domain some-domain.com --lb-cert cert.pem --lb-key key.pem --gcp-service-account-key service-account.key.json
$ bbl up --gcp-service-account-key service-account.key.json
```

**Comment by dsabeti** [comment]
Addressed in this commit: https://github.com/pivotal-cf/onboarding/commit/f7a0a03425f3de64ef7b2ce4f3f03d90f21f6bde
