### ISSUE TITLE
Deploy CF using BOSH instructions contain outdated link

### ISSUE THREAD

**Issue by jzlwang** [pivotal/cf-onboarding#118]
https://www.pivotaltracker.com/story/show/157165712

is
`https://github.com/cloudfoundry/cf-deployment/blob/master/gcp-deployment-guide.md#2-deploying-cf`

should be
`https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md#deploy-cf`

**Comment by dsabeti** [comment]
It looks like this was addressed in this commit: https://github.com/pivotal-cf/onboarding/commit/73aeba4b76043f7eaf98f6d7f0b11a5ae933ae35
