### ISSUE TITLE
nmap story

### ISSUE THREAD

**Issue by jzlwang** [pivotal/cf-onboarding#119]
- After following the instructions, we couldn't get results described in `expected results`
- The story could use more clarity around the intention, as well as things like `YOUR-IP`,`YOUR-INTERNAL-IP`, etc.
- Seems to assume pcfdev -- specifically, it implies that the private IPs should be accessible before modifying ASGs, even though private IPs are excluded in the default cf-deployment. Are these expectations backwards?

**Comment by dsabeti** [comment]
Ok, I think we're going to address this by getting rid of the nmap story in favor a better ASG story: https://github.com/pivotal-cf/onboarding/pull/125
