### ISSUE TITLE
Fix concourse link.

### ISSUE THREAD

**Issue by bwinter** [pivotal/cf-onboarding#120]
For this story: https://www.pivotaltracker.com/story/show/157365921

In the Resources section there is a link "Fly login documentation". It's broken: https://concourse.ci/fly-login.html

**Comment by bwinter** [comment]
Looks like this is the correct link: https://concourse-ci.org/fly.html#fly-login

**Comment by dsabeti** [comment]
Similarly: https://github.com/pivotal-cf/onboarding/pull/124
