### ISSUE TITLE
One more story with some broken links.

### ISSUE THREAD

**Issue by bwinter** [pivotal/cf-onboarding#121]
https://www.pivotaltracker.com/story/show/157365922

https://concourse-ci.org/jobs.html#job-plan
https://concourse-ci.org/jobs.html

**Comment by bwinter** [comment]
Concourse got rid of their single page documentation. Therefore all of the concourse stories with links to concourse documentation have broken links.

**Comment by dsabeti** [comment]
Hey @bwinter. Take a look at this PR: https://github.com/pivotal-cf/onboarding/pull/124. I think it should address your concern.
