### ISSUE TITLE
cf-deployment-vars.yml no longer used to generate cf_admin_password

### ISSUE THREAD

**Issue by kauana** [pivotal/cf-onboarding#133]
Since we are using credhub now, after deploying cf we no longer have a cf-deployment-vars.yml being created.

We need to update the story "Set up your CF target domain" #158573355 (link: https://www.pivotaltracker.com/story/show/158573355) so people can learn how to use credhub in order to get their cf_admin_password.

**Comment by dsabeti** [comment]
Thanks for the feedback @kauana! I've just submitted a PR to address this:
https://github.com/pivotal-cf/onboarding/pull/135. Let's consolidate any discussion on that PR. I'd be happy to hear your feedback there.
