### ISSUE TITLE
generate-csv.go should take in a configuration so that different facilitators can easily customize topics for their week

### ISSUE THREAD

**Issue by dsabeti** [pivotal/cf-onboarding#142]

**Comment by dsabeti** [comment]
Hey @benmoss @dprotaso. I wanted to get your thoughts on this. I think it would be nice for that go script to take in a config or something, so that it's easier for each office/group to customize their tracker project for each week. We find that we sometimes forget to pull in new stories because they're not in the hard-coded list of `.prolific` files.

**Comment by benmoss** [comment]
Maybe there should just be higher-level "modules" or something, like "local/pcfdev" and "gcp/bbl" that group together a bunch of stories. They are ordered and clumped already into something resembling that, but today its more implicit, which I'm guessing is what's leading to your forgotten story problem.

I'd love it if the API for that could be like 

```
generate-tracker-backlog <backlog-id> <api-token> <"gcp" | "local">
```

and it just made the whole thing for you. Maybe even create the project? The sky is the limit.

**Comment by dsabeti** [comment]
We also noticed that some onboarding weeks were getting stale stories by using the "official releases", which haven't been cut since September 2017. What if there was a pipeline that published new releases? Then we wouldn't all have to install `crystal` and prolific on our laptops...

**Comment by dsabeti** [comment]
Similarly, we might just create a docker image that people could use locally so they don't have to download all the dependencies.

**Comment by benmoss** [comment]
I think you can likely use https://github.com/onsi/prolific for this too. I don't know that these prolific files are Crystal-impl specific.

**Comment by dsabeti** [comment]
Closing in favor of https://github.com/pivotal-cf/onboarding/pull/154
