### ISSUE TITLE
Videos to add to tracker

### ISSUE THREAD

**Issue by andrewgilbert12** [pivotal/cf-onboarding#145]
We watched a few videos in our free exploration time that we found interesting, might be a good idea to point to summit talks or some other places to find stuff like that:

https://www.youtube.com/watch?v=5f7Bm1-E3nw
https://www.youtube.com/watch?v=LJO_u7isvtA
https://www.youtube.com/watch?v=0jy3hMt1Zc8
https://www.youtube.com/watch?v=Ru2Q9wyY4ZQ

**Comment by dsabeti** [comment]
Ok, we think we could add a new story to the `projects.prolific` file with these links. We should also ask people to add to the list as they go.
