### ISSUE TITLE
Story request: adding feedback portion

### ISSUE THREAD

**Issue by axyzhao** [pivotal/cf-onboarding#147]
During my onboarding week, we found a handful of usability challenges and questions that I think would be very useful for CF teams to know about. A story in the backlog dedicated to gathering feedback during onboarding week would help communicate these concerns to relevant teams who can consider adjusting UX/design.

New Pivots have a great perspective on many usability issues since they've often had some insight into their team's role in CF, but perhaps not how all components work together. Also, any user feedback is always appreciated!

**Comment by dsabeti** [comment]
I think it makes sense to use this as a chance to talk a bit more about how teams are structured and how they take in feedback -- for example, most teams that Onboarding participants will interact with are open source, and have OSS repos, open slack channels, etc.

It would probably be good to add this story at the end of the epic to deploy cf-deployment -- by that point, they've interacted with bbl, bosh, and cf-deployment, enough to give feedback on.

**Comment by njbennett** [comment]
I've taken a first shot at this in PR #155  but there are still some edits needed. In particular, the pairs in the August cohort all gave feedback on the stories themselves-- which was helpful, but not the intent of the story.

**Comment by njbennett** [comment]
Note to self-- add a bit about contributing to the docs.

#pcf-docs channel
docs-running-cf

**Comment by dsabeti** [comment]
I'm going to close this issue since @njbennett already submitted a PR to add this in.
