### ISSUE TITLE
Notes from onboarding retro

### ISSUE THREAD

**Issue by ljfranklin** [pivotal/cf-onboarding#149]
Some feedback from the last onboarding group that came up during end of week retro:

- Main ask was to record talks so that they could be re-watched at a later time
- Engineers ended up watching lots of videos later in the week and would have appreciated a curated list of videos, e.g. relevant summit talks
- The engineers thought 2 months after starting work at Pivotal would have been the ideal time for them to tackle onboarding week, while the designer thoughts maybe 4 months might be better to have enough context to better understand the stories and ask questions
- Good discussions around a future onboarding week which is tailored to different experience levels and disciplines. For example, adding more stories focused on PM/design skills or adding engineering stories for different experience levels to revisit onboarding week again in a year.

I think the only action item was recording talks during the next onboarding week. The others are maybe just food for thought at this time.

**Comment by dsabeti** [comment]
@njbennett @sjolicoeur, do y'all want to try recording one of the talks next week? It would probably be easier to do this via Zoom.
