### ISSUE TITLE
The latest release is over a year old

### ISSUE THREAD

**Issue by njbennett** [pivotal/cf-onboarding#153]
In the short term we can cut a new release. I'd like to find someone who already knows how to do this and pair on it.

There's probably a bigger change here to either (a) make it easier to build locally and stop publishing releases per se or (b) set up a Concourse pipeline for releases.

**Comment by dsabeti** [comment]
Should we try to get a small Concourse job on wings to build releases any time something is committed to master?

**Comment by njbennett** [comment]
The original task is done.

I think if we want to automate the release building process further (either by scripting the creation of the relevant artifacts into a single command, or building a Concourse pipeline) there should be a separate issue for that work.

**Comment by ljfranklin** [comment]
We now have a release that is two weeks old. Success!
