### ISSUE TITLE
Improvements to the Onboarding Tracker Stories

### ISSUE THREAD

**Issue by StevenLocke** [pivotal/cf-onboarding#156]
1> [Story](https://www.pivotaltracker.com/story/show/159677931) - The BOSH link is broken. It 404s, the correct link is probably `https://bosh.io/docs/`
2> [Story](https://www.pivotaltracker.com/story/show/159677939) - Expected Results says "Visit Menu -> Networking" instead of "Network Services"

**Comment by ljfranklin** [comment]
PR merged!
