### ISSUE TITLE
Concourse docker-compose instructions link to outdated yaml

### ISSUE THREAD

**Issue by willmurphyscode** [pivotal/cf-onboarding#167]
The [docker-compose.yml](https://concourse-ci.org/docker-compose.yml) linked in the [onboarding story](https://github.com/pivotal-cf/onboarding/blob/master/concourse.prolific#L15) points to a file that uses the wrong environment variable to enable users to connect without auth.

The docker-compose.yml file linked in the [tutorial](https://concoursetutorial.com/) uses the correct environment variable.

I don't know whether we should update the onboarding story to point at that tutorial directly, or convince the folks host https://concourse-ci.org/docker-compose.yml to change their file, but right now the directions as written won't work.

Note the presence of `CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH=true` in the tutorial's version of the docker-compose.yml, but not in the one from concourse-ci.org.

**Comment by dsabeti** [comment]
@willmurphyscode, is `CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH=true` the only environment variable that needs to be updated, or are there others?

I think it makes sense to switch to the compose file from the tutorial, since the rest of the Concourse stuff is based on that tutorial.

**Comment by willmurphyscode** [comment]
@dsabeti I think the basic auth username and password have to be set to blank, and then for that setting to actually work, `CONCOURSE_NO_REALLY_I_DONT_WANT_ANY_AUTH` has to be true. Also, I don't think every version of Concourse supports this.

I tried editing the docker-compose file in place rather than using the one from the tutorial, and I remember that I didn't succeed right away, and decided that because I was short on time I'd just use the file from the tutorial, so I'm not completely certain which changes are necessary, but I believe the above is correct.
