### ISSUE TITLE
Update the upload-stemcell command to use Xenial instead of Trusty

### ISSUE THREAD

**Issue by gmrodgers** [pivotal/cf-onboarding#179]
Hey Onboarding team,

We are currently doing onboarding and have found a mismatch between the given command to upload a stemcell and the explanation above the command [here](https://github.com/pivotal-cf/onboarding/blob/0517bf77fe6e43dc28337b2ad104be928a88ba4c/deploy_oss.prolific#L447).

**Comment by dsabeti** [comment]
Ah, it looks like [this PR](https://github.com/pivotal-cf/onboarding/pull/177/files) updated some of the references to the stemcell OS, but not the command for uploading the stemcell.

Would you be willing to open a PR to update the story?

**Comment by selzoc** [comment]
Looks like this was fixed in 46941eeee22f9a5175ed43b6063821ebf382a3e5, closing
