### ISSUE TITLE
Better introduction for how to build Docker images

### ISSUE THREAD

**Issue by oliverswitzer** [pivotal/cf-onboarding#18]
[This intro](https://docs.docker.com/engine/getstarted/step_four/) on docker's website really helped us understand how to build a docker image better than the article linked to in the story (https://www.pivotaltracker.com/story/show/143145055). We ended up installing Docker for Mac and using it that way.

**Comment by keaty** [comment]
Resolved in 2c7a190. Thanks for the suggestion!
