### ISSUE TITLE
story: "Select a stemcell for your BOSH deployment" out of date

### ISSUE THREAD

**Issue by njbennett** [pivotal/cf-onboarding#183]
`bosh upload-stemcell https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-trusty-go_agent?v=VERSION`

should be

`bosh upload-stemcell https://bosh.io/d/stemcells/bosh-google-kvm-ubuntu-xenial-go_agent?v=VERSION`

(trusty --> xenial)

**Comment by dsabeti** [comment]
This looks like a dupe of this github issue: https://github.com/pivotal-cf/onboarding/issues/179. I'll close this out.
