### ISSUE TITLE
Scale the number of Diego Cells

### ISSUE THREAD

**Issue by chenl23** [pivotal/cf-onboarding#185]
bosh interpolate cf-deployment.yml \
  -o ... [any other ops-files you used to deploy orginally] ... \
  -o scale-diego-cells.yml \
  -v system_domain=$SYSTEM_DOMAIN \
  --var-errs

Command did not work when using --var-errs option. 

Error output
pivotals-iMac-3:gcloud-service-account pivotal$ bosh interpolate cf-deployment/cf-deployment.yml -o cf-deployment/operations/scale-diego-cells.yml -o cf-deployment/operations/scale-to-one-az.yml -v system_domain=$SYSTEM_DOMAIN --var-errs
- Expected to find variables:
    - adapter_rlp_tls
    - adapter_tls
    - application_ca
    - blobstore_admin_users_password
    - blobstore_secure_link_secret
    - blobstore_tls
    - cc_bridge_cc_uploader
    - cc_bridge_cc_uploader_server
..
    - uaa_login_saml
    - uaa_ssl

Exit code 1
pivotals-iMac-3:gcloud-service-account pivotal$ 

Interpolate command worked without --var-errs and we were able to deploy foundation.

**Comment by waciuma4pivotal** [comment]
Additionally, it would be very helpful to include information on how to Bosh SSH into our desired cells to use cfdot. One member of the pair knew to run `bosh vms` to acquire the address of a diego cell. WIthout that prior knowledge, we could not use the cfdot documentation. This information could be linked in the resources or explicitly taught.

**Comment by waciuma4pivotal** [comment]
Also of note, the **Expected Result** section of this story expects users to `bosh ssh`, while the following story is to learn how to bosh ssh. Flipping the order of the stories may be helpful.

**Comment by dsabeti** [comment]
Yep, sounds like we need to do two things here:
1. Update the story so that it doesn't include `--var-errs` from the interpolate command (that flag is really only valuable if you aren't using Credhub).
2. Flip the order of the stories so that participants learn to `bosh ssh` before this story.
