### ISSUE TITLE
Docker and Docker Compose install instructions are out of date

### ISSUE THREAD

**Issue by chenl23** [pivotal/cf-onboarding#187]
The Docker link has moved, and https://www.docker.com/community-edition#/download is no longer valid. It redirects to https://www.docker.com/products/docker-engine and now requires an account to download the Docker installers.

Compose is not an extra install on OS X:

> "Install Compose on macOS
> Docker for Mac and Docker Toolbox already include Compose along with other Docker apps, so Mac users do not need to install Compose separately."

**Comment by dsabeti** [comment]
Ok, maybe we can find a simpler way to install with something like Homebrew.
