### ISSUE TITLE
creating OpsMan requires owner permissions

### ISSUE THREAD

**Issue by chenl23** [pivotal/cf-onboarding#188]
`gcloud projects add-iam-policy-binding PROJECT_ID --member 'serviceAccount:ACCOUNT_NAME@PROJECT_ID.iam.gserviceaccount.com' --role 'roles/editor' ` in the initial GCP setup could be changed to `roles/owner` so that the later OpsMan installation is smoother.

We hit continual permissions errors until we were pointed to the very small difference between the docs, (editor vs. owner) which had been very easy to gloss over.

**Comment by dsabeti** [comment]
Yeah, it looks like it depends on how you set up your service account key in the OSS track (the OpsMan stories currently ask you to reuse that service account key). There are two options here:
1. Make sure to update the OSS docs to tell participants to give their service account key owner permissions.
2. Make a new service account key specifically for OpsMan, which has owner permissions.
