### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by professor** [pivotal/cf-onboarding#190]
Story:  Deploy BOSH Director using Ops Manager

```
Configure the BOSH GCP tile using this [guide](https://docs.pivotal.io/pivotalcf/2-2/customizing/gcp-om-config.html). Some tips to keep you from getting stuck:```

The link should be `https://docs.pivotal.io/pivotalcf/2-2/om/gcp/config-manual.html`

**Comment by bwinter** [comment]
This appears to have been resolved here: https://github.com/pivotal/cf-onboarding/commit/30025c9b26e567e1023cbe73a6862109afd19b21#diff-b0fe969cbee2e22a9c01804d520b5147L61
