### ISSUE TITLE
Deploy BOSH Director using Ops Manager story has incorrect link

### ISSUE THREAD

**Issue by beckettsean** [pivotal/cf-onboarding#192]
https://docs.pivotal.io/pivotalcf/2-2/customizing/ops-man.html is a valid link, but not very helpful for the task of configuring the BOSH director.

https://docs.pivotal.io/pivotalcf/2-3/om/gcp/config-terraform.html is the better page to use.

**Comment by ljfranklin** [comment]
We're in the process of overhauling the OpsMgr stories, you can follow along here: https://github.com/pivotal/cf-onboarding/tree/opsman-pas. I updated the doc links on that branch: https://github.com/pivotal/cf-onboarding/commit/7f2a51e6ae36b2b131a3efa1a9cd00e11bb8d201. Going to close this out for now, we're hoping to get the stories updated before next onboarding week.
