### ISSUE TITLE
Story "Pave your IaaS and stand up a BOSH Director with `bbl up`" seems out of order

### ISSUE THREAD

**Issue by tomcharles** [pivotal/cf-onboarding#203]
When the story says to run `bbl print-env` and then `eval "$(bbl print-env)"` we haven't yet run `bbl up`; therefore, the command fails. We create the bbl environment a few steps later.

**Comment by gemmacurlpivotal** [comment]
+1, we ran into this as well

**Comment by pivotalgeorge** [comment]
also, we found that the Docs: What is cf-deployment? link is broken, as the guide.md was moved into texts on master

**Comment by bwinter** [comment]
It looks like this got fixed here: 323708dcbd58c5ea96d197f7c24463fc52ee3429

Thanks for the PR James!
