### ISSUE TITLE
Onboard Chris Selzo As a Facilitator

### ISSUE THREAD

**Issue by selzoc** [pivotal/cf-onboarding#211]
- [x] Meet with a current facilitator to answer questions
- [x] Sign up to shadow onboarding week
- [ ] Shadow an onboarding week
- [ ] Shadow workstation setup
- [ ] Added to facilitor e-mail list
- [x] Added to #sf-onboarding-staff

**Comment by thausler786** [comment]
Assuming the facilitator list for SF is `cf-sf-onboarding-staff`, you should have an invite now.

**Comment by bwinter** [comment]
Closin out old stuffs.
