### ISSUE TITLE
Onboard Carlos Iriarte as a Facilitator

### ISSUE THREAD

**Issue by angelachin** [pivotal/cf-onboarding#220]
- [x] Meet with a current facilitator to answer questions
- [x] Sign up to shadow onboarding week
- [ ] Shadow an onboarding week
- [ ] Shadow workstation setup
- [ ] Added to facilitor e-mail list
- [ ] Added to contributors to `pivotal/cf-onboarding` repo
- [ ] Added to #sf-onboarding-staff

**Comment by bwinter** [comment]
This is pretty old so I am going to close it now.
