### ISSUE TITLE
SF Onboarding Week, January 28, 2018

### ISSUE THREAD

**Issue by thausler786** [pivotal/cf-onboarding#222]
### Communication
- [x] Send out an email to each of the participants. You can find a template in FACILITATING.md.

### IaaS Setup
- [x] Make sure you have GCP projects set up. In SF, we use `cf-sf-onboarding-env-1`, `cf-sf-onboarding-env-2`, and `cf-sf-onboarding-env-3`, which already exist. Otherwise, fill out [this form to create new environments](https://docs.google.com/forms/d/e/1FAIpQLSeJ31997Zma1WtLcCtswiysCFWOG5MXNmlYCpJsiYgdG9kKnA/viewform).
- [x] Clean up any VMs, networks, and DNS records that may have been leftover from the previous week
- [x] Add all participants as **owners** to each of the GCP projects.
- [x] For GCP track **only**: Ensure access to CF-Onboarding-dns project for DNS propagation.

### Tracker Setup
- [x] Make sure you have Tracker projects prepared. Again, in SF we re-use the same tracker projects for [Pair 1](https://www.pivotaltracker.com/n/projects/2125981), [Pair 2](https://www.pivotaltracker.com/n/projects/2125982), and [Pair 3](https://www.pivotaltracker.com/n/projects/2089066).
  1. [x] SF FACILITATORS: Generate and upload Track 2, then move from icebox to backlog
  1. [x] SF FACILITATORS: Generate and upload option/exploratory story set and leave in icebox
- [x] Add all participants as members to each of the tracker projects.

### Workstation Setup
- [x] Make sure you have a workstation for each pair.
- [x] Ensure ethernet cable is plugged into iMac, not monitor.
- [x] Re-image each machine. Here are the steps:
  1. [x] Run `Startup Disk`.
  1. [x] Unlock with the workstation password (you may need to ask the previous facilitator for the machine's password).
  1. [x] Select the network disk and click restart. It will likely be the rightmost start disk, and will definitely include the phrase "Network Disk." If you don't see that, try restarting the machine and try again.
  1. [x] Select deployment option 2, "macOS Sierra" and click the play button. If you look in between the parens of the option name, you'll see the default password for the image. A terminal will open and you’ll see a lot of output, including a bunch of lines that say `installer: PHASE: Running package scripts`. Don’t worry, this is fine. The boot script will search for updates

**Comment by bwinter** [comment]
We finished the workstations Friday
