### ISSUE TITLE
Update number of compilation workers in cloud-config

### ISSUE THREAD

**Issue by wc22222** [pivotal/cf-onboarding#226]
While we are working on the step for "CPU quota / compilation worker story", it's unclear to us what is expected for the CPU quota, we checked on https://console.cloud.google.com by navigating to Home > IAM & Admin > Quotas, it shows a bunch of items. 

We have to locate the service by using the filter to find "Compute Engine API" CPUs with location "us-east1" with "current usage" set as 2, hovering the mouse over it shows 2%. We do not know where sets the quota, if it meets the requirement of "no more than 24 us-east1 CPUs". It would be great if this gets better clarification. 

Additionally, in the cloud-config.yml, we are not sure if we need to modify the default value of 6 for compilation: workers. We wonder how is it matched with the exercise of 2. It would be great if this gets updated so that it would be much clearer for the next trainees. 

Thanks for the consideration!

**Comment by thausler786** [comment]
It looks like there was some confusion about which column to look in in GCP to find the number of CPUs available.  I have made a pull request to point future students to the "Limit" column.

I would appreciate a review of the PR and then we can close this issue.

**Comment by dirkjot** [comment]
+1 , just going through onboarding and found this story not meeting the very high standards of the other stories :-) . 

Given the long list of resources here, I would prefer to add some more instructions on how to filter down, but I'll consider another PR for that.

**Comment by bwinter** [comment]
I believe I merged the PRs that are down stream from this Issue.
