### ISSUE TITLE
[Install Google Cloud SDK] Active configuration as [PROJECT_ID] should be set as "default"?

### ISSUE THREAD

**Issue by wc22222** [pivotal/cf-onboarding#227]
While we are running `gcloud init`, we are prompted "Do you want to configure a default Compute Region and Zone? (Y/n)"  Either we chose Y or n, our current configuration would be set as "default", which does not match the `Your active configuration is : [PROJECT_ID]` in `Expected Result` . 

Please consider updating the expected result if "default" is acceptable. Thanks!

**Comment by thausler786** [comment]
I looked into this issue.  The active configuration that is mentioned in `Your active configuration is : [PROJECT_ID]` is dependent on an earlier step in the configuration than `Do you want to configure a default Compute Region and Zone? (Y/n)`.  

The configuration is actually set here:
```
Pick configuration to use:
 [1] Re-initialize this configuration [default] with new settings 
 [2] Create a new configuration
```
Given that the different pairs' resources are already separated by Project, it seems to me that we can use the default configuration for our resources without problem.  I'll create a PR to update the docs.
