### ISSUE TITLE
"Deploy CF using BOSH + cf-deployment" revisited

### ISSUE THREAD

**Issue by dirkjot** [pivotal/cf-onboarding#254]
We closed  issue [225](https://github.com/pivotal/cf-onboarding/issues/225) two weeks ago but I suddenly found myself doing a mini on-boarding and executing this story during that.  

I used an empty GCP install etc (just not part of onboarding), and found that this story can be reduced to ONE command (basically * ):

```
# assuming you are in your ~/workspace/onboarding directory and ~/workspace/cf-deployment exists

bosh -d cf deploy ../cf-deployment/cf-deployment.yml -v system_domain=$DOMAIN --non-interactive -o ../cf-deployment/operations/use-compiled-releases.yml -o ../cf-deployment/operations/scale-to-one-az.yml
```

For reference, the story points to the [CF-Deployment documentation](https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md), but  that doc is suffering from a bit of sprawl.  Also, of the 8 steps they list, only one is applicable if you have followed the onboarding backlog up to this point. 

 `*` = Ok, I lied, you need to also git clone `cf-deployment`

**Comment by bwinter** [comment]
@dirkjot - did you wind up PRing this? (I know I merged something you added.)

**Comment by dirkjot** [comment]
Think so, I made a PR shortly after the issue.
Thx

**Comment by bwinter** [comment]
Cool, going to close this issue. Thanks!
