### ISSUE TITLE
SF Onboarding, November 4

### ISSUE THREAD

**Issue by bwinter** [pivotal/cf-onboarding#304]
### Communication
- [x] Several weeks before: send out an email to the participants reminding them that they are signed up and to clear their calendars.  You can find a template in [FACILITATING.md](https://github.com/pivotal/cf-onboarding/blob/master/FACILITATING.md).
  - [x] You will be communicating with / authing these folks a lot. I find it helpful to save a copy/pasteable list of their names <emails> here:
    - Gene Hynson <ghynson@pivotal.io>,Jason Kang <jkang@pivotal.io>,Judy van Soldt <jvansoldt@pivotal.io>,Vibhas Kumar <vibkumar@pivotal.io>, Renee Chu <rchu@pivotal.io>
 - ghynson@pivotal.io,jvansoldt@pivotal.io,vibkumar@pivotal.io,jkang@pivotal.io,rchu@pivotal.io

- [x] The week before: send out an email to each of the participants. You can find a template in [FACILITATING.md](https://github.com/pivotal/cf-onboarding/blob/master/FACILITATING.md).
- [x] Get a [Zoom](https://zoom.us/) room setup for remote participants. {<can save link here>}  (Make sure to include this on your calendar invites.)

### Scheduling
- [x] Schedule a welcome/orientation session (1hr at 9:30 Monday morning). Discuss the goals of the week and prime the participants to consider what they'd like to get out of Onboarding week.
- [ ] Schedule daily standup (15min at 9:15, starting Tuesday).
- [x] Schedule afternoon check in (30min at 1:30).
- [x] Schedule retro at the end of the week (1hr at 4:00), include link to retro board: https://retros.cfapps.io/retros/onboarding-sf (pw: onboarding-sf (pls don't change it))
- [ ] Schedule any sessions that you know the group would be interested in -- for example, BOSH boxes and lines.
- [ ] In the past, non Engineers have appreciated it when we blocked out the entire days of onbaording. This is especially helpful if done a few weeks in advance; so, they have time to move meetings and avoid having new ones scheduled in the first place.
---
These are core CF topics, other topics are a bit more "extra credit".
- [ ] BOSH {}
- [ ] CF Overview {}
- [ ] Concourse {}

As a helpful reminder, you can save the name of the speaker w/ checkbox.

### IaaS Setup
- [x] Make sure you have [GCP projects](https://console.cloud.google.com) set up.
  - [ ] In SF, we use:
    - [cf-sf-onboarding-env-1](https://console.cloud.google.com/billing/0076DC-766E1F-EBDCB8/reports?project=cf-sf-onboarding-env-1)
    - [cf-sf-onboarding-env-2](https://console.cloud.google.com/billing/0076DC-766E1F-EBDCB8/reports?project=cf-sf-onboarding-env-2)
    - [cf-sf-onboarding-env-3](https://console.cloud.google.com/billing/0076DC-766E1F-EBDCB8/reports?project=cf-sf-onboarding-env-3)
    - [cf-sf-onboarding-env-4](https://console.cloud.google.com/billing/0076DC-766E1F-EBDCB8/reports?project=cf-sf-onboarding-env-4)
    - [cf-sf-onboarding-env-5](https://console.cloud.google.com/billing/0076DC-766E1F-EBDCB8/reports?project=cf-sf-onboarding-env-5)
  - [N/A] Otherwise, Fill out [this form to create new environments](https://docs.google.com/forms/d/e/1FAIpQLSeJ31997Zma1WtLcCtswiysCFWOG5MXNmlYCpJsiYgdG9kKnA/viewform).
- [x] Clean up any VMs, networks, and DNS records that may have been leftover from the previous week
- [x] Add all [participants](https://docs.google.com/spreadsheets/d/1eW23iJRD56CE859o0j6ArSaGtLfP0JlHXSCdXFhbCdI/edit?usp=sharing) as **owners** to each of the GCP projects.
  - [x] In SF:
    - [IAM for env-1](https://console.cloud.google.com/iam-admin/iam?project=cf-sf-onboarding-env-1)
    - [IAM for env-2](https://console.cloud.google.com/iam-admin/iam?project=cf-sf-onboarding-env-2)
    - [IAM for env-3](https://console.cloud.google.com/iam-admin/iam?project=cf-sf-onboarding-env-3)
    - [IAM for env-4](https://console.cloud.google.com/iam-admin/iam?project=cf-sf-onboarding-env-4)
    - [IAM for env-5](https://console.cloud.google.com/iam-admin/iam?project=cf-sf-onboarding-env-5)
- [N/A] If your CF on-boarding will include the GCP track (`gcp` tracker label / the `oss` build) then ensure participants have access to the `CF-Onboarding-dns` project in GCP (for DNS propagation). [IAM for DNS](https://console.cloud.google.com/iam-admin/iam?project=cf-onboarding-dns)

### Tracker Setup
- [x] Make sure you have Tracker projects prepared.
  - [x] In SF, we use the following trackers projects:
    - [Pair 1](https://www.pivotaltracker.com/n/projects/2125981)
    - [Pair 2](https://www.pivotaltracker.com/n/projects/2125982)
    - [Pair 3](https://www.pivotaltracker.com/n/projects/2089066)
    - [Pair 4](https://www.pivotaltracker.com/n/projects/2361806)
    - [Pair 5](https://www.pivotaltracker.com/n/projects/2361807)
- [x] Add all participants as members to each of the tracker projects. (A list of emails works here.)
- [x] Delete everything from the tracker projects.
  -- Click a top check box and shift+click the bottom checkbox to Select All
  -- Use the trash icon to delete the selected items
- [x] Build the tracker back log csv
  - [x] Run `./build oss` from the onboarding project, this will generate `onboarding-tracker.csv`
       - Note: you need docker installed `brew cask install docker`
         - To get the command line tool to show up you may have to first start docker via Spotlight Search
         - If docker gives you this error: `failed to dial gRPC: unable to upgrade to h2c, received 502 context canceled`
           - In docker settings: enable experimental, restart docker, disable experiment and restart again.
- [x] Import the CSV into each Tracker project (Taskbar > More > Import CSV > Choose File)
   Done for Pair 1, Pair 2 & Pair 3 this time. Pair 4 & Pair 5 skipped.

### LastPass Setup
- [x] Give all participants access to the shared LastPass folder:
  - LastPass > Sharing Center > Shared-CF SF Onboarding > Manage > Invite Users (A list of emails works here.)

### Workstation Setup
Note: local IT departments can sometimes help with workstation setup. (Helpful for remote facilitation.)
- [x] Make sure you have a workstation for each pair.
- [x] Ensure ethernet cable is plugged into iMac, not monitor.
- [x] Re-image each machine. [Here](https://docs.google.com/document/d/1Nya0jMdPAEEtx063xPTatMe6hb_O4oSsrHyUNG-5d1g/edit) are the steps:
- [x] Install dependencies needed for CF Onboarding Week.
   [x] Workstation: Toledo
   [x] Workstation: webster
   [x] Workstation:  king
     ```
     curl -LOk https://github.com/pivotal-cf-experimental/onboarding-week-construct/archive/master.zip
     unzip master.zip
     cd onboarding-week-construct-master
     ./construct
     ```
     You'll need to babysit this process, as it will prompt you for the password several times.

### Misc

- [x] Record any issues you have with this process so we can update this checklist.

#### Issues

**ERRORS ENCOUNTERED during ./construct**  
**ERROR 1** Can't brew tap `cask/caskroom` because it has been moved to `cask/cask`.
FIX ATTEMPT: Change homebrew-casks/install.sh to reference `cask/cask` instead and call ./construct.
**ERROR 2** Can't do an http clone of the homebred-cask Github repository.
FIX ATTEMPT: REPLACE http clone link & call ./construct:
**ERROR 3:** 
```
-* installing cask

sh: cask/install.sh: No such file or directory
```
**FIX ATTEMPT:** 
`cp -r homebrew-casks/ cask/` and rerun ./construct.

**CONCLUSION:** Long-term we need an automated fix that doesn't depend on having a Github SSH key pair.  
```
git clone https://github.com/cask/homebrew-cask /usr/local/Homebrew/Library/Taps/cask/homebrew-cask --depth=1
```
With SSH clone link (needs your Github private SSH key added to the ssh-agent on the workstation in order to work):
```
git clone git@github.com:Homebrew/homebrew-cask.git /usr/local/Homebrew/Library/Taps/cask/homebrew-cask --depth=1

```

----
**ERROR 1 DETAIL:**
`./construct`
We get this error output: 
...
```
==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
-* homebrew installed

-* homebrew already installed

-* installing homebrew-casks

Error: caskroom/cask was moved. Tap homebrew/cask-cask instead.
borked5:onboarding-week-construct-master pivotal$
```

**ERROR 2 DETAIL:**
```
-* installing homebrew-casks
Ignoring path Library/cask/homebrew-cask/
To restore the stashed changes to /usr/local/Homebrew run:
  'cd /usr/local/Homebrew && git stash pop'
==> Tapping cask/cask
Cloning into '/usr/local/Homebrew/Library/Taps/cask/homebrew-cask'...
Username for 'https://github.com': supraja.n@gmail.com
Password for 'https://supraja.n@gmail.com@github.com': 
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/cask/homebrew-cask/'
Error: Failure while executing; `git clone https://github.com/cask/homebrew-cask /usr/local/Homebrew/Library/Taps/cask/homebrew-cask --depth=1` exited with 128.
borked5:onboarding-week-construct-master pivotal$ 
```

**Comment by suprajanarasimhan** [comment]
**Clean up any VMs, networks, and DNS records that may have been leftover from the previous week**

__Compute Engine__
1. Compute Engine > VM Instances - None found
1. Compute Engine > Instance groups - Found & deleted
1. Compute Engine > Disks - None found 
1. Compute Engine > Health Checks - None found
1. Compute Engine > Images 
- Deleted entries that were "Created by cf-sf-onboarding-env-*"
- only delete custom images (there will be a bunch still there that are created by Microsoft,  CentOS, etc)

__VPC Network__
VPC Network - Check all under this one!
1. VPC Networks 
- [ ] Env4 & Env5 to delete
1. Routes 
- [ ] Env4 & Env 5 to delete

__Network Services__
Network Services - All checked but none found.

**Comment by bwinter** [comment]
@suprajanarasimhan  I love all these notes 😍

We should pair on this stuff at some point, I think it would be cool to answer questions and maybe fix some of these issues.

**Comment by bwinter** [comment]
Comments from the retro attendees was that there was some issues with the other pairing stations. That is a little worry some. Maybe we should talk to Jason about that?

Also saw something about using pairist in the post facto notes. That seems like a cool idea for larger groups.

**Comment by bwinter** [comment]
Here is the subject line of that email we wanted to look at as well: "Request updated - [INC-518069] Request for shared Google Drive drive for onboarding staff"

**Comment by bwinter** [comment]
Done and dusted!
