### ISSUE TITLE
Add create-security-group story

### ISSUE THREAD

**Issue by astrieanna** [pivotal/cf-onboarding#32]
A feature of security groups that we didn't use in the security group stories was creating and binding a new security group. This seems to involve writing a json file and then either running a cf command or directly making requests against the cc api (?!).

docs: https://docs.cloudfoundry.org/concepts/asg.html#procedures

**Comment by dsabeti** [comment]
We recently added a story for this: https://github.com/pivotal-cf/onboarding/blob/master/networking_monitoring.prolific#L77-L132
