### ISSUE TITLE
Epic: Create a BOSH release

### ISSUE THREAD

**Issue by zankich** [pivotal/cf-onboarding#34]
Most CF software is intended to be consumed as a BOSH release, so it would be really helpful to have an epic which goes through the entire process.

**Comment by keaty** [comment]
100% agreed. It's next up on the docket.

**Comment by zankich** [comment]
I've started working on stories, so please let me know how'd you like to collaborate!

**Comment by keaty** [comment]
I'd be happy to communicate however works for you, either in the Tracker project you're working in, a Google Doc, or PRs to this repo. One downside to keeping things in Tracker is that collaboration isn't very easy (there's no "comment", just editing) so the latter two options might work best.

**Comment by keaty** [comment]
Hey @zankich, just following up on this. Let me know if you'd like any help on stories!

**Comment by keaty** [comment]
Hey @zankich, I've added a low-explanation Redis BOSH Release story in 9a4f7cf

Let me know if you have thoughts for improvement or additional stories!
