### ISSUE TITLE
Epic: Container networking

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal/cf-onboarding#45]
Have an epic that would cover container networking.

**Comment by keaty** [comment]
@sjolicoeur this is a really great idea! Any chance you're interested in writing it?

**Comment by sjolicoeur** [comment]
@keaty I would, but I am not proficient in container networking yet! I posted this issue because it came up during our retro and I've been making issues before the ideas faded away...

**Comment by keaty** [comment]
@sjolicoeur makes sense! And thank you for posting the issues, it really helps the project progress. I'll put this epic idea in the backlog :)

**Comment by keaty** [comment]
Note: WIP for these stories is in [c2c-networking branch](https://github.com/pivotal-cf/onboarding/tree/c2c-networking)

**Comment by dsabeti** [comment]
It's not an _epic_, but we do have a story for this now: https://github.com/pivotal-cf/onboarding/blob/master/networking_monitoring.prolific#L36-L73. I'll close the issue for now, but I think that if anyone has ideas for expanding it into more of an epic, we can definitely open a new issue with those suggestions.
