### ISSUE TITLE
Clarify the use of the -o switch when using bosh deploy

### ISSUE THREAD

**Issue by sjolicoeur** [pivotal/cf-onboarding#46]
The stories relating to `bosh deploy` should clarify what `-o` does and what the files in the `operations` folder do.

The wording makes the use of the operation folder feel like it must be applied, but in reality the files under `operations` are just options one can activate, and at any time after the creation of a bosh deployed cluster as long as one executes the `bosh deploy`.

**Comment by keaty** [comment]
@sjolicoeur Very good point. I'll look into rewording that story asap.

**Comment by keaty** [comment]
It took me a little while, but I finally got around to making this change in 2065636. Thanks for submitting the issue!

**Comment by sjolicoeur** [comment]
@keaty Great! Thanks!
