### ISSUE TITLE
[Local Track] Need instruction to login as Admin user in story to "Create an org and space"

### ISSUE THREAD

**Issue by jimbosity** [pivotal/cf-onboarding#49]
In this story https://www.pivotaltracker.com/story/show/150296148

Some of us got hung up because we were logged in as User rather than Admin. It would help to have an instruction to login as Admin in this story.

**Comment by jimbosity** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/7897753-116446853_22-s1-v1.png?transparent=1&palette=1&width=246)

**Comment by keaty** [comment]
Thanks, @jimbosity! I'm going to make a few more comments on this issue to capture other challenges from this morning:

* Avoid cloning the `cf-acceptance-tests` repo into `cf-acceptance-tests-master`
* Include instructions to run `cf help` to look for `cf` commands and describe what the USAGE syntax means
* Install cf CLI with installer from Github, not brew
* Reevaluate phrasing of git clone instructions
* For Dora KILL story: "Visit endpoint.." --> in browser
* Explain how to install watch

**Comment by keaty** [comment]
Wrapped up all of these suggestions today. Thanks for the input!
