### ISSUE TITLE
Make nmap networking story instructions clearer

### ISSUE THREAD

**Issue by keaty** [pivotal/cf-onboarding#51]
Describe what traffic we expect to block

**Comment by andrewedstrom** [comment]
+1

When m

**Comment by andrewedstrom** [comment]
Accidentally closed; reopening

**Comment by andrewedstrom** [comment]
Participants in multiple weeks have accidentally ended up scanning the open internet. The story refers to the "IP of the container" but doesn't say how to find out what that IP is, so participants end up guessing and using the wrong IP, such as that of the load balancer

**Comment by dsabeti** [comment]
Heh, we decided to completely get rid of the story and replace it with a new story about ASGs. It uses vanilla `curl` instead of `nmap`.
