### ISSUE TITLE
Generate a TLS cert story should be clearer

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#54]
https://www.pivotaltracker.com/story/show/150192732

It isn't immediately clear from the story that the user must set the path for -keyout and -out. It would be clearer if the intended command were expressed in a way similar to the below:

`openssl req -x509 -newkey rsa:2048 -keyout CHOOSE-PRIVATE-KEY-FILE-NAME.pem -out CHOOSE-CERT-FILE-NAME.pem -nodes`

**Comment by keaty** [comment]
@kdolor-pivotal As discussed, I didn't end up putting the instructions all on one copy/pastable line, but I did make instructions a little more explicit in 23c82dc
