### ISSUE TITLE
Point out where to change the number of compilation workers

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#56]
https://github.com/pivotal-cf/onboarding-week/blob/9f0a832bc848bc696eddea6946d33bd579e403be/deploy_oss.prolific#L260

This should be more clear. In the .yml, you should edit the `workers` line under the `compilation` section.

**Comment by keaty** [comment]
@kdolor-pivotal thanks for the suggestion. I've addressed it in 31d9be4
