### ISSUE TITLE
Incorrect password title

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#57]
https://github.com/pivotal-cf/onboarding-week/blob/9f0a832bc848bc696eddea6946d33bd579e403be/deploy_oss.prolific#L348

Our cf-deployment-vars.yml did not have a key-value pair called `uaa_scim_users_admin_password`. We used `cf_admin_password`.

**Comment by keaty** [comment]
@kdolor-pivotal Thanks for the suggestion, bug fixed in ae1f19e
