### ISSUE TITLE
Should specify how an org is created 

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#58]
https://github.com/pivotal-cf/onboarding-week/blob/5b61e41c51ab4b49d5214ec0643d8e8dfad30aab/app_development.prolific#L7

There was no command that specified how to _create_ an org.

**Comment by keaty** [comment]
@kdolor-pivotal I've made the instructions more explicit in CF Tracker Local (which is the more introductory of the two). I left it as is in CF Tracker OSS. c8260b3
