### ISSUE TITLE
Bosh deploy command should be clearer

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#59]
https://github.com/pivotal-cf/onboarding-week/blob/d5e25ff0911448fc671a20a579c23b7c66ce3876/bosh_troubleshooting.prolific#L7

https://github.com/pivotal-cf/onboarding-week/blob/d5e25ff0911448fc671a20a579c23b7c66ce3876/bosh_troubleshooting.prolific#L7

For step 2: with BOSH CLI v2, you need to do`bosh -d cf deploy cf-deployment.yml`

**Comment by keaty** [comment]
Hey @kdolor-pivotal, fixed in 3028cea
