### ISSUE TITLE
Gateway host setup instructions are incomplete

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#60]
https://github.com/pivotal-cf/onboarding-week/blob/9f0a832bc848bc696eddea6946d33bd579e403be/bosh_troubleshooting.prolific#L24-L28

We had to also do `chmod 0600 bosh.pem`.

The command that eventually worked:
`bosh -e bbl -d cf ssh --gw-host=DIRECTOR-IP --gw-user=jumpbox --gw-private-key=bosh.pem diego-cell/UUID`

**Comment by keaty** [comment]
@kdolor-pivotal thanks for mentioning this, I've included a note to this effect in 79797ce
