### ISSUE TITLE
Incomplete command

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#61]
https://github.com/pivotal-cf/onboarding-week/blob/d5e25ff0911448fc671a20a579c23b7c66ce3876/bosh_troubleshooting.prolific#L101

We had to run `bosh -e bbl -d cf deploy cf-deployment.yml -l cf-deployment-vars.yml`

**Comment by keaty** [comment]
Hey @kdolor-pivotal, this particular one I'm leaving alone, as it's in the OSS track and I would expect users to know from context that `bosh deploy` means the full command (but I did fix the other issue related to the same thing).
