### ISSUE TITLE
Make this more generic for clarity

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#62]
https://github.com/pivotal-cf/onboarding-week/blob/380e3e64d9a680f85528b3357eec64699c5437f3/services_redis_cups.prolific#L37

It is not clear that the placeholder `redis-example-app.my-cloud-foundry.com` should be replaced with the app FQDN

**Comment by keaty** [comment]
Thanks, @kdolor-pivotal! Fixed here 37438b2
