### ISSUE TITLE
Additional detail needed for fly login

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#64]
https://github.com/pivotal-cf/onboarding-week/blob/9f0a832bc848bc696eddea6946d33bd579e403be/concourse.prolific#L41-L44

We had to run: `fly -t NAME-OF-DEPLOYMENT login --username=CONCOURSE-USERNAME --password=CONCOURSE-PASSWORD --CONCOURSE-URL=https://CONCOURSE-FQDN -k`

**Comment by keaty** [comment]
Thanks, @kdolor-pivotal! I've addressed this in 6537ad0
