### ISSUE TITLE
Insufficient instruction on how to create a Concourse job

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#65]
https://github.com/pivotal-cf/onboarding-week/blob/88ae060459b65ee3beaae61a8050ed96b72b45ec/concourse.prolific#L62

How to create a job should be further explained. The linked concourse documentation does not provide much clarity.

**Comment by dsabeti** [comment]
We've decided to try leveraging the [Stark & Wayne tutorial](concoursetutorial.com) for learning up on Concourse: https://github.com/pivotal-cf/onboarding/blob/concourse/concourse.prolific#L61-L79. I'm going to close the issue, but we may want to revisit the decision and re-write the stories ourselves, depending on the feedback from future onboarding weeks.
