### ISSUE TITLE
Further explanation of what a Concourse task does is needed 

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#66]
https://github.com/pivotal-cf/onboarding-week/blob/88ae060459b65ee3beaae61a8050ed96b72b45ec/concourse.prolific#L82

Concourse documentation doesn't specify what a task actually _performs_. Further explanation regarding how tasks fit into the larger purpose of this section would be appreciated.

**Comment by dsabeti** [comment]
We've decided to try leveraging the [Stark & Wayne tutorial](concoursetutorial.com) for learning up on Concourse: https://github.com/pivotal-cf/onboarding/blob/concourse/concourse.prolific#L61-L79. I'm going to close the issue, but we may want to revisit the decision and re-write the stories ourselves, depending on the feedback from future onboarding weeks.
