### ISSUE TITLE
Examples here would be helpful

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#67]
https://github.com/pivotal-cf/onboarding-week/blob/88ae060459b65ee3beaae61a8050ed96b72b45ec/concourse.prolific#L100

Examples/inspiration would have been helpful in this step.

**Comment by keaty** [comment]
@kdolor-pivotal Thanks for the suggestion, I've updated the instructions to be more specific in d7d6a26
