### ISSUE TITLE
Tag and push instructions should be made clear

### ISSUE THREAD

**Issue by kdolor-pivotal** [pivotal/cf-onboarding#68]
https://github.com/pivotal-cf/onboarding-week/blob/88ae060459b65ee3beaae61a8050ed96b72b45ec/concourse.prolific#L99

The Dockerhub documentation doesn't go into great detail so it'd be helpful to call this out. We had to run the following:

`docker tag IMAGE-NAME DOCKER-HUB-USER-ID/IMAGE-NAME` 

`docker push DOCKER-HUB-USER-ID/IMAGE-NAME` 

*Docker hub user ID to be used in this command is not the user's email address. Consult the DockerHub "My Profile" section to verify what the username should be.

**Comment by keaty** [comment]
Hey @kdolor-pivotal, I think I'm going to leave this part as is to encourage deeper exploration of Docker documentation and investigation of the right way to push.
