### ISSUE TITLE
Re-write app development stories on OSS Track to require use of the API instead of the CLI

### ISSUE THREAD

**Issue by keaty** [pivotal/cf-onboarding#71]
Leave the prescriptive app development stories to the Local track, upgrade OSS track app development stories to push an app **using the API**. This is an excellent way to gain a greater understanding of what is happening under the hood when you `cf push`.  e.g. https://github.com/cloudfoundry/cloud_controller_ng/wiki/How-to-Create-an-App-Using-V3-of-the-CC-API

**Comment by dsabeti** [comment]
- Start with a simpler command, like `cf create-org`
- Then work up to `cf push`. Maybe make this an exercise in reverse engineering, using the doc above plus `CF_TRACE`
- Separate epic that participants can opt in to

**Comment by ljfranklin** [comment]
We recently added an optional story to push an app using CAPI's v3 API here: https://github.com/pivotal/cf-onboarding/pull/151/files. We also have another request to add an introduction to CAPI's API here: https://github.com/pivotal/cf-onboarding/issues/110. Going to close this out in favor of the other open story but feel free to re-open if I'm missing something.
