### ISSUE TITLE
Improve / re-write generate-tracker-csv.go to be less buggy

### ISSUE THREAD

**Issue by keaty** [pivotal/cf-onboarding#75]
... and ideally, no longer require the user `go build` it.

Or maybe just update the `prolific` tool to accept multiple files as arguments.

**Comment by ljfranklin** [comment]
While still a little janky, we do have a build script now: https://github.com/pivotal/cf-onboarding/blob/master/build. As this issue is pretty stale I'm going to close it out but someone can re-open if they're still feeling pain around the build script.
