### ISSUE TITLE
Need `brew tap cloudfoundry/tap` to `brew install bosh-cli` 

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#77]
The user would need to first run `brew tap cloudfoundry/tap` to `brew install bosh-cli`. The instructions are also on the github page here: https://github.com/cloudfoundry/homebrew-tap

**Comment by dsabeti** [comment]
Hi @shubhaat. This commit includes the updated instructions: https://github.com/pivotal-cf/onboarding/commit/927aa4e29ae7c6de7ccacc9d426e388fa684da13
