### ISSUE TITLE
Add link to what the roles can do and give workshop participants `Owner` roles so they can give the service account `Editor` permissions

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#78]
The participants need `Owner` permissions to give `Editor` role to service account

https://cloud.google.com/iam/docs/understanding-roles#primitive_roles

**Comment by dsabeti** [comment]
I've started a checklist for facilitators to use. It includes instructions to add participants as project owners: https://github.com/pivotal-cf/onboarding/pull/138
