### ISSUE TITLE
Stemcell version for #152585752 should either be what is in the `cf-deployment.yml` file or the file needs to be updated to the latest version

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#79]
cf deployments fail because the version of the stemcell is not available. We set the version in the previous story (#152585750). We should either set this to what is in the manifest or the manifest should be updated to use the latest version. 

https://github.com/cloudfoundry/cf-deployment/blob/master/deployment-guide.md

**Comment by dsabeti** [comment]
Hey @shubhaat. I've added a commit that should address this problem: https://github.com/pivotal-cf/onboarding/commit/aa0157101e4d054db64ac35c6879a8e5779a8f4e
