### ISSUE TITLE
Story Deploy CF using BOSH + cf-deployment should be more explicit about link to repo

### ISSUE THREAD

**Issue by zgagnon** [pivotal/cf-onboarding#8]
The story https://www.pivotaltracker.com/story/show/142952109 contains instructions to clone the repo, which is linked earlier in the story. This is a little confusing as there is not really an indication that the link goes to a repo, or an association between the word "repo" and the link.

Suggestion:

Make the word "repo" the link to the repository.

**Comment by zgagnon** [comment]
Also, please call out that the instructions are for creating a bosh deployment repo (right now, it links to that, which is confusing on larger screens).

**Comment by keaty** [comment]
Fixed. Thanks for the feedback!
