### ISSUE TITLE
Watch needs to be installed for Pivotal tracker story #152585764

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#80]
To run `watch cf app dora`, attendees would need to install watch for [this story](https://www.pivotaltracker.com/n/projects/2125981) by running `brew install watch` before running the command.

**Comment by dsabeti** [comment]
Here you go: https://github.com/pivotal-cf/onboarding/commit/bc0c5873b9041dc03a9e1b5f632c7b105166e126
