### ISSUE TITLE
bosh deploy command should take an environment 

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#81]
The command specified in the [story](https://www.pivotaltracker.com/story/show/152585777) is: 
`bosh -d DEPLOYMENT_NAME deploy MANIFEST`

The command should have **specified the environment**, such as: 
`bosh -e my-env -d my-dep deploy manifest.yml [-v ...] [-o ...]`

**Comment by dsabeti** [comment]
Hi @shubhaat. The stories instruct users to run `eval "$(bbl print-env)"`, which replaces the use of `-e`.
