### ISSUE TITLE
Incomplete instructions for "Scale Number of Diego Cells" story

### ISSUE THREAD

**Issue by shubhaat** [pivotal/cf-onboarding#82]
This issue applies to the onboarding story [Scale Number of Diego Cells](https://www.pivotaltracker.com/story/show/152585777).

Current instructions:

1. Edit the number of Diego Cell instances in the manifest. (If you do this, BOSH will take the number of instances of all the jobs from the manifest as well, which will make it take a long time to run.)
2. Perform a deploy using bosh -d DEPLOYMENT_NAME deploy MANIFEST (Incomplete instructions.)
3. Observe the new VM appearing by running bosh vms (Yes!)

Recommended changes for these instructions:
- Specify an enviroment with -e.
- A better way to scale the number of Diego Cells is to refer to two operations files when you submit the bosh cf deploy command.
   - Ops file 1: Use the scale-to-one-az.yml operations file to make the process run more quickly.
   - Ops file 2: Create and use a new ops file specifying the number of Diego Cell instances. Call this ops file **after** you call scale-to-one-az.yml so that the new ops file takes priority. That new file could read as follows:

```
- type: replace
  path: /instance_groups/name=diego-cell/instances
  value: 4
```

**Comment by andrewedstrom** [comment]
Additional notes from @jimbosity:

> For this story: https://www.pivotaltracker.com/story/show/153951795
>
> It doesn't specify that we should edit the operations file (.yml) to scale up the diego cell instances. Rather, it suggests altering the "MANIFEST" - if the user alters the primary manifest (cf-deployment.yml), the command will scale up all sorts of things. This is because in the original story to deploy CF, we use the operations file.
> Also, the command is given as bosh -d DEPLOYMENT_NAME deploy MANIFEST - though it needs to include -o OPERATIONS FILE

**Comment by dsabeti** [comment]
I think this commit should clarify how to best update the manifest: https://github.com/pivotal-cf/onboarding/commit/6e67f06516faedea153ca16ef2693a0844ddbb37. It explicitly walks you though creating an ops-file.
