### ISSUE TITLE
Scaling up Diego Cells story is confusing

### ISSUE THREAD

**Issue by jimbosity** [pivotal/cf-onboarding#89]
For this story: https://www.pivotaltracker.com/story/show/153951795 

1. It doesn't specify that we should edit the operations file (.yml) to scale up the diego cell instances. Rather, it suggests altering the "MANIFEST" - if the user alters the primary manifest (cf-deployment.yml), the command will scale up all sorts of things. This is because in the original story to deploy CF, we use the operations file.
2. Also, the command is given as `bosh -d DEPLOYMENT_NAME deploy MANIFEST` - though it needs to include `-o OPERATIONS FILE`

**Comment by andrewedstrom** [comment]
Closing as this seems to be a repeat of #82 . @jimbosity I copied your comments into that story to make sure they don't get lost
