### ISSUE TITLE
Freenom doesn't work

### ISSUE THREAD

**Issue by jimbosity** [pivotal/cf-onboarding#90]
In the initial stories to create a new domain, it suggests using Freenom.com. Both pairs during this onboarding week were unable to edit their domains (and update their nameservers) once the freenom accounts were created.

**Comment by dsabeti** [comment]
I've got a PR that should remove Freenom as a dependency: https://github.com/pivotal-cf/onboarding/pull/130

**Comment by dsabeti** [comment]
I'm going to close this issue now that the PR has been merged. Thanks @jimbosity!
