### ISSUE TITLE
`SSH into a running BOSH job` story is out of date

### ISSUE THREAD

**Issue by jrussett** [pivotal/cf-onboarding#97]
This story: https://github.com/pivotal-cf/onboarding/blob/955551322f3e9ebc148b5ce76e3a0f1ce2b05fb4/bosh_troubleshooting.prolific#L20-L38 
no longer makes sense as the more recent versions of BBL automatically create a jumpbox and change the `bosh ssh` behavior.

**Comment by dsabeti** [comment]
Thanks for the feedback @jrussett. I'll update the story.

**Comment by SocalNick** [comment]
Addressed in https://github.com/pivotal-cf/onboarding/pull/109

**Comment by zankich** [comment]
This has been fixed, thanks for reporting the issue!
